import "./src/style/style.scss";
import heroAva from "./src/assets/img/hero/hero-2.jpg";
import leptop from "./src/assets/img/about/leptop.png";
import anime from "./src/assets/img/about/anime.jpg";
import rock from "./src/assets/img/about/rock.png";
import gitara from "./src/assets/img/about/gitara.png";
import logoHtml from "./src/assets/svg/skills/html-1.svg";
import logoCss from "./src/assets/svg/skills/css-3.svg";
import logoSass from "./src/assets/svg/skills/sass-1.svg";
import logoGit from "./src/assets/svg/skills/git-icon.svg";
import logoGitHub from "./src/assets/svg/skills/github_logo.svg";
import logoJS from "./src/assets/svg/skills/javascript-1.svg";
import logoPython from "./src/assets/svg/skills/python-5.svg";
import logoFigma from "./src/assets/svg/skills/figma.svg";
import game from "./src/assets/img/project/random-game.PNG";
import tutorial from "./src/assets/img/project/tutorial.png";
import mail from "./src/assets/img/contact/adress.png";
import myGit from "./src/assets/svg/github_logo.svg";
import logoSchool from "./src/assets/svg/rs-school-logo.svg";

document.querySelector(".hero__ava").src = heroAva;
document.querySelectorAll(".about-me__photo")[0].src = leptop;
document.querySelectorAll(".about-me__photo")[1].src = anime;
document.querySelectorAll(".about-me__photo")[2].src = rock;
document.querySelectorAll(".about-me__photo")[3].src = gitara;
document.querySelectorAll(".skills__img")[0].src = logoHtml;
document.querySelectorAll(".skills__img")[1].src = logoCss;
document.querySelectorAll(".skills__img")[2].src = logoSass;
document.querySelectorAll(".skills__img")[3].src = logoGit;
document.querySelectorAll(".skills__img")[4].src = logoGitHub;
document.querySelectorAll(".skills__img")[5].src = logoJS;
document.querySelectorAll(".skills__img")[6].src = logoPython;
document.querySelectorAll(".skills__img")[7].src = logoFigma;
document.querySelectorAll(".projects__img")[0].src = game;
document.querySelectorAll(".projects__img")[1].src = tutorial;
document.querySelectorAll(".contact__img")[0].src = mail;
document.querySelectorAll(".contact__img")[1].src = myGit;
document.querySelectorAll(".contact__img")[2].src = logoSchool;
